Reorganización del código
algoritmos-iii/algo3_notas pull request #1
Opened 2021-08-25 21:30 UTC by josuebouchard

- Meti los archivos del codigo del programa en una carpeta llamada `src` para asi separarla de archivos de configuracion
- Agregue type hints a las funciones de `notas.py` y `notas_oauth.py`
- Renombre el archivo `notasweb.py` a `main.py` para denotar que es el archivo principal que hay que ejecutar y asi separarlo del resto
- Extraje la clase `PadronYMailFormulario` que estaba en `notasweb.py` y lo puse dentro de un archivo propio dentro de una carpeta llamada `forms`
- Puse dentro de `PadronYMailFormulario` los metodos necesarios para que la clase pueda devolver los campos normalizados (funcion sacada de `notasweb.py`)
- A las funciones que no deberian ser "publicas" les puse el guion bajo como prefijo
- Algunos cambios de nombres para hacer mas entendible el codigo

2021-09-02 21:23 UTC, julitaras requested changes

2021-09-02 21:23 UTC, julitaras commented on src/main.py
> +APP_TITLE = f'{os.environ["NOTAS_COURSE_NAME"]} - Consulta de Notas'
la `f` ?

2021-09-02 21:23 UTC, julitaras commented on src/repositories/sendmail.py
> +#!/usr/bin/env python3
Mas que `repository` lo veo como un `service`

2021-09-02 21:23 UTC, julitaras commented on src/repositories/google_credentials.py
> +from __future__ import annotations
Este tampoco lo veo parte de repository!

2021-09-02 23:01 UTC, josuebouchard commented on src/main.py
> +APP_TITLE = f'{os.environ["NOTAS_COURSE_NAME"]} - Consulta de Notas'
Una decision de diseño. Permite la interpolación de strings. En esta ocasión fue más una decisión. Si de repente no te gusta, podemos dejar la anterior.

2021-09-02 23:03 UTC, josuebouchard commented on src/repositories/google_credentials.py
> +from __future__ import annotations
El annotations viene como un deficit del sistema de type hints, en python 10 va a dejar de estar en `__future__` y va a pasar a estar como default.
En resumen, se necesita por un tema de los type hints mezclada a la naturaleza dinamica de python. Es un tema de python, no del modelo en si.

2021-09-02 23:05 UTC, julitaras commented on src/repositories/google_credentials.py
> +from __future__ import annotations
me refiero al file, ya que el objetivo es obtener las credenciales

2021-09-02 23:05 UTC, julitaras commented on src/main.py
> +APP_TITLE = f'{os.environ["NOTAS_COURSE_NAME"]} - Consulta de Notas'
Oka!

2021-09-02 23:05 UTC, josuebouchard commented on src/repositories/sendmail.py
> +#!/usr/bin/env python3
Tenes razon, en el proximo commit muevo `repositories/sendmail.py -> services/sendmail.py` y arreglo los imports en el `main.py`

2021-09-02 23:15 UTC, josuebouchard commented on src/repositories/google_credentials.py
> +from __future__ import annotations
Ah... lei mal el cambio. En realidad vendria a ser una especie de helper o dependencia de `NotasRepository` y `EmailSender` que se encarga de obtener las credenciales que se necesitan, pero no supe bien como categorizarlo. Podria hacer un folder `dependencies` o `shared` y poner ahi `google_credentials.py`, ya que habria que mover `repositories/sendmail.py -> services/sendmail.py`.

2021-09-02 23:18 UTC, josuebouchard commented on src/repositories/sendmail.py
> +#!/usr/bin/env python3
Otra cosa, tambien habria que renombrar `EmailSender` a `EmailSenderService`, o se sobreentiende?

2021-09-02 23:23 UTC, julitaras commented on src/repositories/google_credentials.py
> +from __future__ import annotations
Si, sino puede estar en una especie de `config`

2021-09-02 23:23 UTC, julitaras commented on src/repositories/google_credentials.py
> +from __future__ import annotations
O una carpeta `api`

2021-09-02 23:38 UTC, josuebouchard commented on src/repositories/google_credentials.py
> +from __future__ import annotations
Creo que preferiria ponerlo en `api`, principalmente porque en si no se encarga de la configuracion per se (todo eso esta en el `main.py`, sino que se encarga de obtener datos (más precisamente, credenciales). Por eso lo habia dejado en primer lugar en repository.

2021-09-03 02:22 UTC, julitaras commented on src/repositories/google_credentials.py
> +from __future__ import annotations
dale

2021-09-03 18:40 UTC, julitaras approved these changes
Excelente laburo!

2021-09-03 19:03 UTC, merged